using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Serialization;
using Object = UnityEngine.Object;

public class StaticMeshAudioEmitter : MonoBehaviour
{
    public bool autoGenerated = false;
    public string meshName;
    public AudioClip associatedAudioClip;
    public MeshFilter linkedMeshFilter;

    public bool hasPositionOffset = false;
    private Vector3 _originalMeshPosition;

    public Vector3 ReferencePosition
    {
        get => hasPositionOffset ? _originalMeshPosition : transform.position;
        set
        {
            transform.position = hasPositionOffset ? (transform.position - _originalMeshPosition) + value : value;
            _originalMeshPosition = value;
        }
    }

}
